### ISSUE TITLE
Support display of extra fields

### ISSUE THREAD

**Issue by balmas** [perseids-tools/treebank-react#1]
there are a number of extra fields supported by Arethusa:

On the sentence: 
cite

On the word:
sg
comment
artificial
gloss
alternateGloss
semanticRole
include
multiword
notes

Will the viewer support displaying these?

**Comment by balmas** [comment]
Not that  the `artificial` attribute affects th display of the text with a smaller font style in Arethusa:

![b20a7a67-ddf1-43ca-ae63-c99113529b7e](https://user-images.githubusercontent.com/644870/98012139-bf96e700-1dc6-11eb-9123-a8fea7f757c8.png)
![d9cd8724-c44b-439c-9f11-eb4d3e98a185](https://user-images.githubusercontent.com/644870/98012197-d0475d00-1dc6-11eb-85b0-3530522c7181.png)

**Comment by zfletch** [comment]
Created https://github.com/perseids-tools/treebank-react/issues/15 to keep track of the changes needed for `artificial` attributes. This issue will be for the fields listed in the description.
