### ISSUE TITLE
Consider how the treebank could be controlled externally

### ISSUE THREAD

**Issue by zfletch** [perseids-tools/treebank-react#8]
Some applications that use the library may want to control the active word or other internal state. There should be (optional) props for setting these and callbacks for when they are set. There may also need to be an option for only calling the callback and not modifying the internal state at all.

**Comment by balmas** [comment]
Alpheios would need the following API functions through which it can retrieve the data from the tree:

Function: getMorph
Description: Gets the morphology + any extra attributes (gloss, comment, etc) for a specific word
Input Parameters: sentenceId, wordId
Response:  a JSON object (ideally adhering to a JSON representation of Alpheios Lexicon Schema)

Function: findWord
Description: finds a word in a sentence (chunk) given a specific context (preceding, following words)
Input Parameters : sentenceId, word, prefix, suffix
Response: wordId

For navigation, it needs to be able to navigate the tree to a specific sentence, by sentenceId, with the ability to preselect a word or a subsection of the sentence by wordId

**Comment by zfletch** [comment]
Thanks @balmas! The navigation and `getMorph` functionality should be pretty easy. Figuring out the best way to implement `findWord` will take a little more work.

**Comment by balmas** [comment]
Re findWord, maybe we could port some of that code from Arethusa? https://github.com/alpheios-project/arethusa/blob/widget/app/js/arethusa.search/services/search.js

**Comment by zfletch** [comment]
I'm looking at the [relevant code](https://github.com/perseids-publications/treebank-template/blob/ad063450389312a6c7990587dd5bec4da8e88fd5/src/components/TreebankService/TreebankService.js#L74) in the Treebank Template ~~and it looks to me like it doesn't currently support selecting a word. Is there another piece of code that handles it that I'm not seeing? Or is that feature not currently supported?~~

I'm also not sure there's a good way to select more than one word at once. Do you think that's a necessary feature? Selecting a single word through the props shouldn't be a difficult feature to add.

**Comment by zfletch** [comment]
@balmas sorry, ignore the first part of my previous comment, I was looking in the wrong place. Selecting multiple words is done with the `?w=` parameter, e.g. [https://perseids-publications.github.io/gorman-trees/aeschines-1-1-50-bu1/2?w=3,4,5](https://perseids-publications.github.io/gorman-trees/aeschines-1-1-50-bu1/2?w=3,4,5).

The question we need to answer is whether that's a necessary feature or not. The architecture of this library assumes there's only one selected word. The morphology box, for example, only shows the morphology of the active word. If that feature is necessary, we could add highlighting to multiple words. But I'd want to make the color different, so highlighted words aren't confused for the active word.

**Comment by balmas** [comment]
I don't know of a use case for selecting more than one word at a time, although we do have the request to highlight an entire branch from a word.

**Comment by zfletch** [comment]
That makes sense. For this issue, I think we should limit selection to a single word. I've created another issue (https://github.com/perseids-tools/treebank-react/issues/25) to keep track of highlighting multiple words.
